server:
  port: 8090

spring:
  application:
    name: tdg-sentinel-client
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8888
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
